"""initial_schema

Revision ID: adc9cd8c8220
Revises: 
Create Date: 2026-09-27 13:01:04.147390

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'adc9cd8c8220'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('pickup_hour_ts', sa.DateTime(), nullable=False),
    sa.Column('trip_count', sa.Float(), nullable=False),
    sa.Column('pickup_hour', sa.Integer(), nullable=False),
    sa.Column('pickup_dow', sa.Integer(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('snowfall', sa.Float(), nullable=True),
    sa.Column('is_holiday', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'pickup_hour_ts')
    )
    op.create_index(op.f('ix_demand_history_zone_id'), 'demand_history', ['zone_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('n_estimators', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('predicted_trips', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_demand_history_zone_id'), table_name='demand_history')
    op.drop_table('demand_history')
    # ### end Alembic commands ###
